# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549ee7b5ae7585810d7f6726f172b8f6bd4830ca1c2ab038700d2fe74e592bab4427cfb69aba1014bbf9f24351d57f07093f031314673cfce3b18ab62bc66338

test:
  secret_key_base: 4edf19bc0143a90e691c241f45006d9ed125fcb87a9e782785fe8ab348988a990c7bfbe949d1ab274fee40903cd6324af1c06771b944e07d1ab75e2343c9c2b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
